//<auto-generated/>
namespace WebDav
{
    /// <summary>
    /// Specifies a type of lock - exclusive or shared.
    /// </summary>
    public enum LockScope
    {
        Shared,
        Exclusive
    }
}
