//<auto-generated/>
using System.Net.Http;

namespace WebDav
{
    internal static class WebDavMethod
    {
        public static readonly HttpMethod Propfind = new HttpMethod("PROPFIND");

        public static readonly HttpMethod Proppatch = new HttpMethod("PROPPATCH");

        public static readonly HttpMethod Mkcol = new HttpMethod("MKCOL");

        public static readonly HttpMethod Copy = new HttpMethod("COPY");

        public static readonly HttpMethod Move = new HttpMethod("MOVE");

        public static readonly HttpMethod Lock = new HttpMethod("LOCK");

        public static readonly HttpMethod Unlock = new HttpMethod("UNLOCK");

        public static readonly HttpMethod Search = new HttpMethod("SEARCH");
    }
}
