// <auto-generated />
namespace Bili.Copilot.Libs.Flyleaf.Controls;

public interface IMediaTransportControls
{
    bool Player_CanHideCursor();
    bool Player_GetFullScreen();
    void Player_SetFullScreen(bool value);
    void Player_Disposed();
}
