// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

namespace Bili.Copilot.App.Controls.Markdown;

public interface IImageProvider
{
    Task<Image> GetImage(string url);
    bool ShouldUseThisProvider(string url);
}
