// <auto-generated />

global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Windows.ApplicationModel;
global using Windows.ApplicationModel.Activation;
global using Windows.Foundation;
