// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using Markdig.Renderers;
using Markdig.Syntax;

namespace Bili.Copilot.App.Controls.Markdown.Renderers;

public abstract class WinUIObjectRenderer<TObject> : MarkdownObjectRenderer<WinUIRenderer, TObject>
where TObject : MarkdownObject
{
}
