// Copyright (c) Bili Copilot. All rights reserved.
// <auto-generated />

namespace Bili.Copilot.Models.BiliBili.Player;

public class VideoPageResponse
{
    public string bvid { get; set; }
    public long aid { get; set; }
    public long tid { get; set; }
    public string tname { get; set; }
    public int copyright { get; set; }
    public string pic { get; set; }
    public string title { get; set; }
    public long pubdate { get; set; }
    public long ctime { get; set; }
    public string desc { get; set; }
    public int state { get; set; }
    public int duration { get; set; }
    public int mission_id { get; set; }
    public PublisherInfo owner { get; set; }
    public VideoStatusInfo stat { get; set; }
    public string dynamic { get; set; }
    public long cid { get; set; }
    public int season_id { get; set; }
    public UgcSeason ugc_season { get; set; }
    public bool is_season_display { get; set; }
    public string like_icon { get; set; }
    public bool need_jump_bv { get; set; }
    public bool disable_show_up_info { get; set; }
    public int is_story_play { get; set; }
    public List<VideoPageSubPart> pages { get; set; }
}

public class VideoPageSubPart
{
    public long cid { get; set; }
    public int page { get; set; }
    public string from { get; set; }
    public string part { get; set; }
    public int duration { get; set; }
    public string vid { get; set; }
    public string weblink { get; set; }
    public string first_frame { get; set; }
}

public class UgcSeason
{
    public int id { get; set; }
    public string title { get; set; }
    public string cover { get; set; }
    public long mid { get; set; }
    public string intro { get; set; }
    public int sign_state { get; set; }
    public int attribute { get; set; }
    public List<VideoPageSection> sections { get; set; }
    public int ep_count { get; set; }
    public int season_type { get; set; }
    public bool is_pay_season { get; set; }
    public int enable_vt { get; set; }
}

public class VideoPageSection
{
    public int season_id { get; set; }
    public int id { get; set; }
    public string title { get; set; }
    public int type { get; set; }
    public List<VideoEpisode> episodes { get; set; }
}

public class VideoEpisode
{
    public int season_id { get; set; }
    public int section_id { get; set; }
    public int id { get; set; }
    public int aid { get; set; }
    public int cid { get; set; }
    public string title { get; set; }
    public int attribute { get; set; }
    public VideoEpisodeArc arc { get; set; }
    public string bvid { get; set; }
}

public class VideoEpisodeArc
{
    public long aid { get; set; }
    public int videos { get; set; }
    public int copyright { get; set; }
    public string pic { get; set; }
    public string title { get; set; }
    public int pubdate { get; set; }
    public int ctime { get; set; }
    public string desc { get; set; }
    public int state { get; set; }
    public int duration { get; set; }
    public PublisherInfo author { get; set; }
    public VideoStatusInfo stat { get; set; }
    public string dynamic { get; set; }
    public bool is_chargeable_season { get; set; }
    public bool is_blooper { get; set; }
    public int enable_vt { get; set; }
    public string vt_display { get; set; }
}
